syntax = "proto3";

option csharp_namespace = "CatService";

package cat;

import "google/protobuf/timestamp.proto";
import "common/pagination.proto";


service Cats {
  // Get list of cats
  rpc ListCats (ListCatsRequest) returns (ListCatsResponse);
  // Get cat by id
  rpc GetCat (GetCatRequest) returns (GetCatResponse);
  //Create new cat
  rpc CreateCat (CreateCatRequest) returns (CreateCatResponse);
}

enum Breed {
  DOMESTIC_CAT = 0;
  MAINE_COON = 1;
  RAGDOLL = 2;
  SPHYNX = 3;
  PERSIAN = 4;
  BRITISH_SHORTHAIR = 5;
  AMERICAN_SHORTHAIR = 6;
  SIBERIAN = 7;
}

enum CatStatus {
  UNAVAILABLE = 0;
  BOOKED = 1;
  AVAILABLE = 2;
}

enum CatActivity {  
  IDLE = 0;
  PLAYING = 1;
  EATING = 2;
  RESTING = 3;
  GROOMING = 4;
  VET_CARE = 5;
}

message  CatItem {
  int32 id = 1;
  string name = 2;
  int32 age = 3;
  Breed breed = 4;
  CatStatus status = 5;
  CatActivity activity = 6;
  google.protobuf.Timestamp created_at = 7;
}

message ListCatsRequest {
  common.pagination.PaginationRequest pagination = 1;
  optional CatStatus status = 2;
  optional CatActivity activity = 3;
}

message ListCatsResponse {
  repeated CatItem cats = 1;
  common.pagination.PaginationResponse pagination = 2;
}

message GetCatRequest {
  int32 id = 1;
}

message GetCatResponse {
  CatItem cat = 1;
}

message CreateCatRequest{
  string name = 1;
  int32 age = 2;
  Breed breed = 3;
}

message CreateCatResponse {
  CatItem cat = 1;
}