syntax = "proto3";

option csharp_namespace = "CatService";

package cat;

import "google/protobuf/timestamp.proto";
import "common/pagination.proto";
import "google/protobuf/empty.proto";


service Cats {
  // Get list of cats
  rpc ListCats (ListCatsRequest) returns (ListCatsResponse);
  // Get cat by id
  rpc GetCat (GetCatRequest) returns (GetCatResponse);
  //Create new cat
  rpc CreateCat (CreateCatRequest) returns (CreateCatResponse);
  // Set external activity
  rpc StartExternalActivity(StartExternalActivityRequest) returns (google.protobuf.Empty);
  // Remove cat by id
  rpc DeleteCat(DeleteCatRequest) returns (google.protobuf.Empty);
}

enum Breed {
  DOMESTIC_CAT = 0;
  MAINE_COON = 1;
  RAGDOLL = 2;
  SPHYNX = 3;
  PERSIAN = 4;
  BRITISH_SHORTHAIR = 5;
  AMERICAN_SHORTHAIR = 6;
  SIBERIAN = 7;
}

enum Activity {  
  IDLE = 0;
  PLAYING = 1;
  EATING = 2;
  RESTING = 3;
  GROOMING = 4;
  VET_CARE = 5;
  WITH_VISITOR = 6;
}

message CatActivityState {
  Activity activity = 1;
  google.protobuf.Timestamp start_time = 2;
  google.protobuf.Timestamp end_time = 3;
  optional int32 external_activity_id = 4;
}

enum Gender {
  MALE = 0;
  FEMALE = 1;
}

message  CatItem {
  int32 id = 1;
  string name = 2;
  int32 age = 3;
  Gender gender = 4;
  Breed breed = 5;
  CatActivityState cat_activity_state = 6;
  google.protobuf.Timestamp created_at = 7;
}

message ListCatsRequest {
  common.pagination.PaginationRequest pagination = 1;
  optional Activity activity = 3;
}

message ListCatsResponse {
  repeated CatItem cats = 1;
  common.pagination.PaginationResponse pagination = 2;
}

message GetCatRequest {
  int32 id = 1;
}

message GetCatResponse {
  CatItem cat = 1;
}

message CreateCatRequest{
  string name = 1;
  int32 age = 2;
  optional Gender gender = 3;
  Breed breed = 4;
}

message CreateCatResponse {
  CatItem cat = 1;
}

message StartExternalActivityRequest{
  int32 cat_id = 1;
  Activity activity = 2;
  int32 external_activity_id = 3;
  google.protobuf.Timestamp start_time = 4;
  google.protobuf.Timestamp end_time = 5; 
}

message DeleteCatRequest{
  int32 id = 1;
}