// <auto-generated />
using System;
using CatService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatService.Migrations
{
    [DbContext(typeof(CatCafeDbContext))]
    [Migration("20260929134659_AddExternalActivityState")]
    partial class AddExternalActivityState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatService.Data.Entities.CatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ActivityEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_ends_at");

                    b.Property<DateTimeOffset?>("ActivityStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activity_started_at");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<int>("Breed")
                        .HasColumnType("integer")
                        .HasColumnName("breed");

                    b.Property<int>("CatActivity")
                        .HasColumnType("integer")
                        .HasColumnName("activity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ExternalActivityId")
                        .HasColumnType("integer")
                        .HasColumnName("external_activity_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Breed = 0,
                            CatActivity = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Gender = 0,
                            Name = "Барсик"
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            Breed = 0,
                            CatActivity = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Gender = 1,
                            Name = "Мурка"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Breed = 0,
                            CatActivity = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Gender = 0,
                            Name = "Васька"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
